FROM rust:slim-bookworm AS build

WORKDIR /build
COPY Cargo.toml .
COPY crates/ crates/

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        pkg-config libssl-dev

RUN cargo build --release

FROM gcr.io/distroless/static-debian11:latest

WORKDIR /lemmy
COPY ui/ ui/
COPY --from=build /build/target/release/liblemmy_search_common.rlib bin/liblemmy_search_common.rlib
COPY --from=build /build/target/release/lemmy-search-crawler bin/lemmy-search-crawler
COPY --from=build /build/target/release/lemmy-search bin/lemmy-search

EXPOSE 8000
ENTRYPOINT [ "/lemmy/bin/lemmy-search", "/lemmy/ui" ]
