FROM lukemathwalker/cargo-chef:latest-rust-slim AS chef
WORKDIR /cache

FROM chef as planner

# We only pay the installation cost once, 
# it will be cached from the second build onwards
#RUN cargo install cargo-chef 
COPY server/ ./
RUN cargo chef prepare --recipe-path recipe.json

FROM chef as cacher

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        pkg-config libssl-dev

#RUN cargo install cargo-chef
COPY --from=planner /cache/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust:slim-bookworm AS build

WORKDIR /build
COPY server/ server/
COPY --from=cacher /cache/target/ server/target/

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        pkg-config libssl-dev

RUN cargo build --manifest-path=server/Cargo.toml --release

FROM debian:stable-slim AS deps
RUN cd /tmp && \
    apt-get update && \
    apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
        --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends \
        network-manager grep dnsmasq libzstd1 | \
        grep "^\w") && \
    mkdir /dpkg && \
    for deb in *.deb; do dpkg --extract $deb /dpkg || exit 10; done

FROM gcr.io/distroless/static-debian11:latest

WORKDIR /lemmy
COPY ui/ ui/
COPY config/ config/
COPY --from=deps /dpkg /
COPY --from=build /build/server/target/release/lemmy-search bin/lemmy-search

EXPOSE 8000
ENTRYPOINT [ "/lemmy/bin/lemmy-search", "/lemmy/ui" ]
